### ISSUE TITLE
Criação dos RestControllers (Classe de recursos)de consumo endpoint para. Listagem ID e Serviço(PR1)

### ISSUE THREAD

**Issue by GabrielaSabrine** [GabrielaSabrine/helpr#1]
- [x] Criação de classe de cliente resource, cliente service e cliente dto. 
- [x] Criou o RestController dentro de cliente resource
- [x] Listagem de ID no service

**Comment by soulcode-acad** [comment]
Olá Gaby tudo bem? Vamos lá seu trabalho está muito legal noto bom código e foco nos problemas, faltou limpeza de código sabe linhas puladas demais e "tals" poderia prejudicar um dev futuro. Faltou etiquetar as tarefas ou entregas para ajudar o revisor e assinar as tarefas entregues, inclusive ficou uma sem correção de entrega. De resto parabéns foi show evolução a olhos vistos.

![image](https://user-images.githubusercontent.com/100297907/172864748-49804660-673d-4404-a5e9-a0def67c66b0.png)
